name: Generate Metrics Doc

on:
  pull_request:
    branches: [ "main" ]

jobs:
  generate-metrics-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Generate Metrics Doc
        run: |
          ./scripts/generate_metrics_doc.sh

      - name: Commit Generated Metrics Doc
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/METRICS.md"
          default_author: github_actions
          message: "chore: automatic generate metrics doc in docs folder"
